### ISSUE TITLE
Support pre-feeding a botan repo path

### ISSUE THREAD

**Issue by NtWriteCode** [Tectu/botan-cmake#2]
I like bringing my botan as a submodule and it would be amazing if I could feed this cmake the path where to find it instead of downloading the botan tarball.

I know, downloading of 10ish megs doesn't take too much time, but still, it'd be nice if I could make my compilation/build process working completely offline too.

Do you think it's feasible? I think the config/build script is not polluting the actual botan repository, so doing multiple builds on the same repo without entirely wiping/resetting the folder should not be an issue, or is it?

**Comment by Tectu** [comment]
That should definitely be possible - I don't see anything preventing us from doing that from the top of my head.
I'll put this on the ToDo list for the weekend :)

**Comment by NtWriteCode** [comment]
Just created a possible implementation:
https://github.com/Tectu/botan-cmake/pull/3

I'm not the most experienced in cmake, but seemed decent enough

**Comment by opswat-roland-gyorffi** [comment]
I think we can close this now :)

**Comment by Tectu** [comment]
Merged - Thank you for your contribution!
