### ISSUE TITLE
Possibility to Enable All Modules With a Keyword

### ISSUE THREAD

**Issue by TxMat** [Tectu/botan-cmake#4]
When starting a new empty project it can be a bit frustrating to enable all features one by one. it'll be useful to have to possibility to enable them all at once

exemple :

replace

```swift
botan_generate(
    botan_target
        system_rng
        sha3
        hmac
        uuid
        ... # ommited for brievety
        auto_rng
)
```

with

```swift
botan_generate(
    botan_target
        all_features
)
```

**Comment by Tectu** [comment]
Reasonable suggestion!

How about having all modules enabled as a default, i.e.:
```cmake
botan_generate(botan_target)
```
Will simply enable all modules (instead of `all_features`)?

**Comment by TxMat** [comment]
Even better !

**Comment by Tectu** [comment]
Can you give the updated `FindBotan.cmake` in the `feature/all_modules` branch a try?
If you call `botan_generate()` without any module parameters (just the target name) it should now automatically include all modules. Which appears to be like 244 :D

**Comment by TxMat** [comment]
Almost, it seems enabling all module made boost a required dependency (which i do not have installed) causing the compilation to fail.

```
====================[ Build | botanned | Debug ]================================
/home/dummy_user/.local/share/JetBrains/Toolbox/apps/clion-nova/bin/cmake/linux/x64/bin/cmake --build /home/dummy_user/CLionProjects/botanned/cmake-build-debug --target botanned -j 22
[0/1] Re-running CMake...
-- Botan amalgamation modules for target "botan_target": adler32;aead;aes;-- snip --;zfec_vperm;zlib
-- Configuring done (1.1s)
-- Generating done (0.0s)
-- Build files have been written to: /home/dummy_user/CLionProjects/botanned/cmake-build-debug
[1/6] Building CXX object CMakeFiles/botan_target.dir/botan_all.cpp.o
FAILED: CMakeFiles/botan_target.dir/botan_all.cpp.o 
/usr/bin/c++   -g -std=gnu++20 -fPIC -fdiagnostics-color=always -MD -MT CMakeFiles/botan_target.dir/botan_all.cpp.o -MF CMakeFiles/botan_target.dir/botan_all.cpp.o.d -o CMakeFiles/botan_target.dir/botan_all.cpp.o -c /home/dummy_user/CLionProjects/botanned/cmake-build-debug/botan_all.cpp
In file included from /home/dummy_user/CLionProjects/botanned/cmake-build-debug/botan_all.cpp:8:
/home/dummy_user/CLionProjects/botanned/cmake-build-debug/botan_all.h:2634:13: fatal error: boost/version.hpp: No such file or directory
 2634 |    #include <boost/version.hpp>
      |             ^~~~~~~~~~~~~~~~~~~
compilation terminated.
[2/6] Scanning /home/dummy_user/CLionProjects/botanned/main.cpp for CXX dependencies
FAILED: CMakeFiles/botanned.dir/main.cpp.o.ddi 
/usr/bin/c++  -I/home/dummy_user/CLionProjects/botanned/cmake-build-debug -g -std=gnu++20 -fdiagnostics-color=always -E -x c++ /home/dummy_user/CLionProjects/botanned/main.cpp -MT CMakeFiles/botanned.dir/main.cpp.o.ddi -MD -MF CMakeFiles/botanned.dir/main.cpp.o.ddi.d -fmodules-ts -fdeps-file=CMakeFiles/botanned.dir/main.cpp.o.ddi -fdeps-target=CMakeFiles/botanned.dir/main.cpp.o -fdeps-format=p1689r5 -o CMakeFiles/botanned.dir/main.cpp.o.ddi.i
In file included from /home/dummy_user/CLionProjects/botanned/main.cpp:5:
/home/dummy_user/CLionProjects/botanned/cmake-build-debug/botan_all.h:2634:13: fatal error: boost/version.hpp: No such file or directory
 2634 |    #include <boost/version.hpp>
      |             ^~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by Tectu** [comment]
Yeah no... there is no chance that this CMake script is going to handle Botan module specific dependencies for you.
That would require maintaining a dependency tree ourselves.

Generally I don't think that having this "enable all modules" feature all that helpful - exactly because of issues like this (and just bloat in general).

**Comment by TxMat** [comment]
What about keeping this feature but warn the user that he will now be responsible for installing the required packages ?

**Comment by Tectu** [comment]
I don't think that such a warning would be reasonable to add. Keep in mind that the same situation applies if you were not to use this new "add-all-modules" feature but just manually listing a Botan module that requires dependencies. We'd need to print such a warning conditionally then - which would again requiring maintaining a manual dependency tree - or just always printing out the warning, which is also not helpful :)

These things are rarely as straight forward as they seem.

**Comment by Tectu** [comment]
After long consideration I decided not to add this feature as per the reasons already outlined in this discussion.
